mlst_dir:
  /home/mjsull/curr_proj/gono/ngpipe/mlst
ppng_fasta:
  /home/mjsull/curr_proj/gono/ngpipe/data/ppng_target.fasta
rplf_fasta:
  /home/mjsull/curr_proj/gono/ngpipe/data/rplf_target.fasta
rrna_fasta:
  /home/mjsull/curr_proj/gono/ngpipe/data/rrna_target.fasta
position1:
  2045
position2:
  2597
read_dir:
  none
contig_dir:
  none
