mlst_dir:
  /path/to/tseemann/mlst
ppng_fasta:
  /path/to/ngpipe/data/ppng_target.fasta
rplf_fasta:
  /path/to/ngpipe/data/rplf_target.fasta
rplf_fasta:
  /path/to/ngpipe/data/rrna_target.fasta
position1:
  2045
position2:
  2597
read_dir:
  none
contig_dir:
  none