mlst_dir:
  /data/ngono/ngpipe/mlst
ppng_fasta:
  /data/ngono/ngpipe/data/ppng_target.fasta
rplf_fasta:
  /data/ngono/ngpipe/data/rplf_target.fasta
rrna_fasta:
  /data/ngono/ngpipe/data/rrna_target.fasta
position1:
  2045
position2:
  2597
read_dir:
  none
contig_dir:
  none
previous_runs:
  none
strict:
  true
